#!/usr/bin/env node
import http from "node:http";
import process from "node:process";
import { WebSocketServer } from "ws";

const HOST="127.0.0.1",PORT=Number(process.env.PIXEL_FLOW_BRIDGE_PORT||43128);
const clients=new Map(),pending=new Map(),tasks=new Map();let primaryClientId=null;
const json=(res,status,value)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","access-control-allow-headers":"content-type","access-control-allow-methods":"GET,POST,OPTIONS"});res.end(JSON.stringify(value))};
const body=req=>new Promise((resolve,reject)=>{const chunks=[];req.on("data",chunk=>chunks.push(chunk));req.on("end",()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")||"{}"))}catch(error){reject(error)}});req.on("error",reject)});
const active=()=>[...clients.values()].filter(client=>client.socket.readyState===1&&Date.now()-client.lastSeen<30_000);
const publicClient=client=>({clientId:client.clientId,projectId:client.projectId,title:client.title,revision:client.revision,primary:client.clientId===primaryClientId});
const pick=input=>input?.clientId?active().find(client=>client.clientId===input.clientId):input?.projectId?active().find(client=>client.projectId===input.projectId):active().find(client=>client.clientId===primaryClientId);
const setPrimary=id=>{primaryClientId=id;for(const client of active())client.socket.send(JSON.stringify({type:"primary",primary:client.clientId===id}))};

const server=http.createServer(async(req,res)=>{if(req.method==="OPTIONS")return json(res,204,{});const url=new URL(req.url||"/",`http://${HOST}:${PORT}`);try{
  if(req.method==="GET"&&url.pathname==="/health")return json(res,200,{ok:true,version:1,ready:Boolean(pick()),primaryClientId,connectedClients:active().map(publicClient)});
  if(req.method==="POST"&&url.pathname==="/primary"){const data=await body(req),client=active().find(item=>item.clientId===data.clientId);if(!client)return json(res,404,{ok:false,error:"Pixel Flow tab is not connected."});setPrimary(client.clientId);return json(res,200,{ok:true,primary:publicClient(client)})}
  if(req.method==="GET"&&url.pathname.startsWith("/tasks/")){const task=tasks.get(decodeURIComponent(url.pathname.slice(7)));return task?json(res,200,task):json(res,404,{ok:false,error:"Unknown requestId"})}
  if(req.method==="POST"&&url.pathname==="/rpc"){const data=await body(req);if(!data.requestId||!data.action)return json(res,400,{ok:false,error:"requestId and action are required."});if(tasks.has(data.requestId))return json(res,200,tasks.get(data.requestId));const client=pick(data);if(!client)return json(res,503,{ok:false,error:"No Pixel Flow canvas is connected."});if(data.action!=="getState"&&Number.isInteger(data.expectedRevision)&&data.expectedRevision!==client.revision)return json(res,409,{ok:false,error:`Revision conflict: expected ${data.expectedRevision}, current ${client.revision}.`,revision:client.revision});const task={ok:true,requestId:data.requestId,status:"running",action:data.action,clientId:client.clientId,createdAt:new Date().toISOString()};tasks.set(data.requestId,task);const timer=setTimeout(()=>{pending.delete(data.requestId);Object.assign(task,{ok:false,status:"failed",error:"Pixel Flow response timed out."});json(res,504,task)},Math.min(Math.max(Number(data.timeoutMs)||30_000,1000),120_000));pending.set(data.requestId,{res,timer,task});client.socket.send(JSON.stringify({type:"task",requestId:data.requestId,action:data.action,payload:data.payload||{}}));return}
  return json(res,404,{ok:false,error:"Not found"});
}catch(error){return json(res,400,{ok:false,error:error instanceof Error?error.message:String(error)})}});
const wss=new WebSocketServer({noServer:true});server.on("upgrade",(req,socket,head)=>{if(new URL(req.url||"/",`http://${HOST}:${PORT}`).pathname!=="/canvas")return socket.destroy();wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws))});
wss.on("connection",socket=>{let clientId="";socket.on("message",raw=>{let message;try{message=JSON.parse(String(raw))}catch{return}if(message.type==="hello"){clientId=String(message.clientId||"");if(!clientId)return socket.close(1008,"clientId required");clients.set(clientId,{clientId,projectId:String(message.projectId||""),title:String(message.title||"Pixel Flow"),revision:Number(message.revision)||0,lastSeen:Date.now(),socket});if(!pick())setPrimary(clientId);socket.send(JSON.stringify({type:"welcome",primary:clientId===primaryClientId}));return}const client=clients.get(clientId);if(!client)return;client.lastSeen=Date.now();if(message.type==="status"){client.projectId=String(message.projectId||client.projectId);client.revision=Number(message.revision)||0;return}if(message.type==="result"){const entry=pending.get(message.requestId);if(!entry)return;clearTimeout(entry.timer);pending.delete(message.requestId);client.revision=Number(message.revision)||client.revision;Object.assign(entry.task,message.error?{ok:false,status:"failed",error:message.error}:{ok:true,status:"succeeded",result:message.result},{revision:client.revision});json(entry.res,message.error?409:200,entry.task)}});socket.on("close",()=>{clients.delete(clientId);if(clientId===primaryClientId)setPrimary(active()[0]?.clientId||null)})});
server.listen(PORT,HOST,()=>process.stderr.write(`Pixel Flow bridge listening on http://${HOST}:${PORT}\n`));
const shutdown=()=>{for(const client of clients.values())client.socket.close();wss.close();server.close()};process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);
