import { useEffect, useRef } from "react";
import { db } from "./db";
import { useStore } from "./store";
import type { CanvasNode, TaskNode } from "./types";

const BRIDGE_URL="ws://127.0.0.1:43128/canvas";
const clientId=()=>{const key="pixel-flow-bridge-client-id";let value=sessionStorage.getItem(key);if(!value){value=crypto.randomUUID();sessionStorage.setItem(key,value)}return value};
const revision=()=>useStore.getState().project?.updatedAt??0;
const stateSnapshot=()=>{const state=useStore.getState(),project=state.project;return{ready:state.ready,revision:revision(),currentProjectId:project?.id,projects:state.projects.map(item=>({id:item.id,name:item.name,updatedAt:item.updatedAt,nodeCount:item.graph.nodes.filter(node=>!("hidden" in node&&node.hidden)).length})),project:project?{...project,graph:{nodes:project.graph.nodes.filter(node=>!("hidden" in node&&node.hidden)),edges:project.graph.edges.filter(edge=>!project.graph.nodes.some(node=>("hidden" in node&&node.hidden)&&(node.id===edge.source||node.id===edge.target)))}}:null,selectedNodeIds:state.selected}};
const blobDataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});

async function executeOne(command:Record<string,unknown>){const store=useStore.getState(),op=String(command.op||"");
  if(op==="canvas.create"){await store.createProject();const created=useStore.getState().project;if(created&&command.name)await useStore.getState().renameProject(String(command.name),created.id);return{projectId:created?.id}}
  if(op==="canvas.open"){await store.openProject(String(command.projectId));return{projectId:String(command.projectId)}}
  if(op==="canvas.delete"){const projectId=String(command.projectId||store.project?.id||"");await store.deleteProject(projectId);return{deletedProjectId:projectId,currentProjectId:useStore.getState().project?.id}}
  if(op==="task.create"){const position=(command.position&&typeof command.position==="object"?command.position:{x:620,y:220}) as {x:number,y:number};await store.addTask(position,Array.isArray(command.sourceNodeIds)?command.sourceNodeIds.map(String):[]);const taskId=useStore.getState().selected[0];await useStore.getState().updateNode(taskId,{prompt:String(command.prompt||""),generationMode:command.generationMode==="browser"?"browser":"api",aspectRatio:String(command.aspectRatio||"auto")} as Partial<TaskNode>);return{taskId}}
  if(op==="task.run"){await store.runTask(String(command.taskId));const task=useStore.getState().project?.graph.nodes.find((node):node is TaskNode=>node.id===command.taskId&&node.kind==="task");return{taskId:String(command.taskId),status:task?.status}}
  if(op==="task.duplicate"){await store.duplicateTask(String(command.taskId));return{taskId:useStore.getState().selected[0]}}
  if(op==="task.delete"||op==="node.delete"){store.setSelected([String(command.taskId||command.nodeId)]);await useStore.getState().deleteSelected();return{deletedId:String(command.taskId||command.nodeId)}}
  if(op==="node.move"){await store.moveNode(String(command.nodeId),command.position as {x:number,y:number});return{nodeId:String(command.nodeId)}}
  if(op==="history.undo"){await store.restoreDeleted();return{undone:true}}
  throw new Error(`Unsupported Pixel Flow command: ${op}`);
}
async function handle(action:string,payload:Record<string,unknown>){if(action==="getState")return stateSnapshot();if(action==="getImage"){const project=useStore.getState().project,node=project?.graph.nodes.find(candidate=>candidate.id===payload.nodeId) as CanvasNode|undefined;if(!node||!(node.kind==="image"||node.kind==="result"))throw new Error("Image/result node was not found in the current canvas.");const asset=await db.assets.get(node.assetId);if(!asset)throw new Error("The image asset is missing.");return{nodeId:node.id,title:node.kind==="image"?node.title:(node.title||"生成结果"),dataUrl:await blobDataUrl(asset.blob)}}if(action==="execute"){const commands=Array.isArray(payload.commands)?payload.commands:[payload.commands];const results=[];for(const command of commands){if(!command||typeof command!=="object")throw new Error("Each command must be an object.");results.push(await executeOne(command as Record<string,unknown>))}return{results,state:stateSnapshot()}}throw new Error(`Unsupported bridge action: ${action}`)}

export function PixelFlowCodexBridge(){const socket=useRef<WebSocket|null>(null);useEffect(()=>{let stopped=false,timer=0;const sendStatus=()=>{const ws=socket.current,state=useStore.getState();if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"status",projectId:state.project?.id,revision:state.project?.updatedAt??0}))};const connect=()=>{if(stopped)return;const ws=new WebSocket(BRIDGE_URL);socket.current=ws;ws.onopen=()=>ws.send(JSON.stringify({type:"hello",clientId:clientId(),projectId:useStore.getState().project?.id,title:document.title,revision:revision()}));ws.onmessage=async event=>{let message;try{message=JSON.parse(String(event.data))}catch{return}if(message.type!=="task")return;try{const result=await handle(String(message.action),message.payload||{});ws.send(JSON.stringify({type:"result",requestId:message.requestId,result,revision:revision()}))}catch(error){ws.send(JSON.stringify({type:"result",requestId:message.requestId,error:error instanceof Error?error.message:String(error),revision:revision()}))}};ws.onclose=()=>{if(!stopped)timer=window.setTimeout(connect,1500)}};connect();const heartbeat=window.setInterval(sendStatus,10_000);const unsubscribe=useStore.subscribe(sendStatus);return()=>{stopped=true;window.clearTimeout(timer);window.clearInterval(heartbeat);unsubscribe();socket.current?.close()}},[]);return null}
