import { useEffect, useRef } from "react";
import { db } from "./db";
import { useStore } from "./store";
import type { CanvasNode, TaskNode } from "./types";

const BRIDGE_URL="ws://127.0.0.1:43128/canvas";
const LIBRARY_STORAGE_KEY="pixelFlowMvpLibraryV1";
const clientId=()=>{const key="pixel-flow-bridge-client-id";let value=sessionStorage.getItem(key);if(!value){value=crypto.randomUUID();sessionStorage.setItem(key,value)}return value};
const revision=()=>useStore.getState().project?.updatedAt??0;
const stateSnapshot=()=>{const state=useStore.getState(),project=state.project;return{ready:state.ready,revision:revision(),currentProjectId:project?.id,projects:state.projects.map(item=>({id:item.id,name:item.name,updatedAt:item.updatedAt,nodeCount:item.graph.nodes.filter(node=>!("hidden" in node&&node.hidden)).length})),project:project?{...project,graph:{nodes:project.graph.nodes.filter(node=>!("hidden" in node&&node.hidden)),edges:project.graph.edges.filter(edge=>!project.graph.nodes.some(node=>("hidden" in node&&node.hidden)&&(node.id===edge.source||node.id===edge.target)))}}:null,selectedNodeIds:state.selected}};
const blobDataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});
type LibraryMedia={id:string;kind:string;name?:string;tags?:string[];[key:string]:unknown};
type LibraryPrompt={id:string;name?:string;content?:string;tags?:string[];exampleAssetId?:string;[key:string]:unknown};
type LocalLibrary={prompts?:LibraryPrompt[];media?:LibraryMedia[];presets?:Record<string,unknown>;templates?:unknown[];[key:string]:unknown};
const normalizeTags=(tags:unknown)=>[...new Set((Array.isArray(tags)?tags:[]).map(tag=>String(tag||"").trim()).filter(Boolean))];
const readLocalLibrary=():LocalLibrary=>{try{return JSON.parse(localStorage.getItem(LIBRARY_STORAGE_KEY)||"{}") as LocalLibrary}catch{return{}}};
const saveLocalLibrary=(library:LocalLibrary)=>{localStorage.setItem(LIBRARY_STORAGE_KEY,JSON.stringify(library));window.dispatchEvent(new CustomEvent("pixel-flow:library-updated"))};
const makeId=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
const dataUrlBlob=(value:unknown)=>{const match=String(value||"").match(/^data:([^;,]+);base64,([A-Za-z0-9+/=\s]+)$/);if(!match)throw new Error("imageDataUrl must be a base64 data URL.");const binary=atob(match[2].replace(/\s/g,"")),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index+=1)bytes[index]=binary.charCodeAt(index);return new Blob([bytes],{type:match[1]})};
const productSeriesTag=(name:string)=>{const text=name.replace(/^durex-pd-\d+\s*[|｜]\s*/i,"");if(/^001/i.test(text))return"001系列";if(/^超薄/i.test(text))return"超薄系列";if(/^AiR/i.test(text))return"AiR系列";if(/^玻尿酸/.test(text))return"玻尿酸系列";if(/^草莓/.test(text))return"草莓系列";if(/^持久/.test(text))return"持久系列";return""};
const productPackageTag=(name:string)=>/铝箔/.test(name)?"铝箔":/包装盒/.test(name)?"包装盒":"";
const productSnapshot=()=>{const library=readLocalLibrary();return(library.media||[]).filter(item=>item.kind==="product").map(item=>({id:item.id,name:String(item.name||""),tags:normalizeTags(item.tags)}))};
const scopeKind=(scope:string)=>scope==="products"?"product":scope==="references"?"reference":"";
const librarySnapshot=async(scope="all")=>{const library=readLocalLibrary(),prompts=(scope==="all"||scope==="prompts"?(library.prompts||[]):[]).map(item=>({id:item.id,name:String(item.name||""),content:String(item.content||""),tags:normalizeTags(item.tags),exampleAssetId:String(item.exampleAssetId||"")})),media=(library.media||[]).filter(item=>scope==="all"||item.kind===scopeKind(scope)).map(item=>({id:item.id,kind:item.kind,name:String(item.name||""),tags:normalizeTags(item.tags),assetId:String(item.assetId||"")}));const assetIds=[...new Set([...prompts.map(item=>item.exampleAssetId),...media.map(item=>item.assetId)].filter(Boolean))],assets=await db.assets.bulkGet(assetIds);const available=new Set(assets.filter(Boolean).map(asset=>asset!.id));return{scope,prompts,media,missingAssetIds:assetIds.filter(id=>!available.has(id))}};

async function importLibrary(command:Record<string,unknown>){
  const scope=String(command.scope||""),preview=command.preview!==false,mode=command.mode==="replace"?"replace":"merge",items=Array.isArray(command.items)?command.items:[];
  if(!["prompts","products","references"].includes(scope))throw new Error("library.import scope must be prompts, products, or references.");
  const errors:Array<{index:number,error:string}>=[],normalized:Array<Record<string,unknown>>=[];
  items.forEach((raw,index)=>{try{if(!raw||typeof raw!=="object")throw new Error("item must be an object");const item=raw as Record<string,unknown>,name=String(item.name||"").trim();if(!name)throw new Error("name is required");const tags=normalizeTags(item.tags);if(scope==="prompts"){const content=String(item.content||"").trim();if(!content)throw new Error("content is required");normalized.push({name,content,tags,imageDataUrl:item.imageDataUrl})}else{if(!item.imageDataUrl&&!item.assetId)throw new Error("imageDataUrl or assetId is required");normalized.push({name,tags,imageDataUrl:item.imageDataUrl,assetId:item.assetId})}}catch(error){errors.push({index,error:error instanceof Error?error.message:String(error)})}});
  if(errors.length)return{preview,scope,mode,total:items.length,valid:normalized.length,errors};
  const library=readLocalLibrary();library.prompts=library.prompts||[];library.media=library.media||[];
  const existing=scope==="prompts"?library.prompts:library.media.filter(item=>item.kind===scopeKind(scope)),existingNames=new Set(existing.map(item=>String(item.name||""))),created=normalized.filter(item=>!existingNames.has(String(item.name))),updated=normalized.filter(item=>existingNames.has(String(item.name)));
  if(preview)return{preview:true,scope,mode,total:normalized.length,created:created.map(item=>item.name),updated:updated.map(item=>item.name),removed:mode==="replace"?existing.filter(item=>!normalized.some(next=>next.name===item.name)).map(item=>item.name):[]};
  const storeAsset=async(item:Record<string,unknown>,fallback="")=>{if(item.imageDataUrl){const assetId=makeId("asset");await db.assets.put({id:assetId,blob:dataUrlBlob(item.imageDataUrl),createdAt:Date.now()});return assetId}const assetId=String(item.assetId||fallback);if(!assetId)return"";if(!await db.assets.get(assetId))throw new Error(`Asset not found: ${assetId}`);return assetId};
  if(scope==="prompts"){
    const next=mode==="replace"?[]:[...library.prompts];
    for(const item of normalized){const current=next.find(entry=>entry.name===item.name),exampleAssetId=await storeAsset(item,String(current?.exampleAssetId||""));const record={...(current||{}),id:current?.id||makeId("prompt"),name:String(item.name),content:String(item.content),tags:normalizeTags(item.tags),exampleAssetId,updatedAt:Date.now()};if(current)Object.assign(current,record);else next.push(record)}library.prompts=next;
  }else{
    const kind=scopeKind(scope),next=mode==="replace"?library.media.filter(item=>item.kind!==kind):[...library.media];
    for(const item of normalized){const current=next.find(entry=>entry.kind===kind&&entry.name===item.name),assetId=await storeAsset(item,String(current?.assetId||""));const record={...(current||{}),id:current?.id||makeId("media"),kind,name:String(item.name),tags:normalizeTags(item.tags),assetId,createdAt:Number(current?.createdAt)||Date.now()};if(current)Object.assign(current,record);else next.push(record)}library.media=next;
  }
  saveLocalLibrary(library);return{preview:false,scope,mode,total:normalized.length,created:created.length,updated:updated.length,library:await librarySnapshot(scope)};
}

async function executeOne(command:Record<string,unknown>){const store=useStore.getState(),op=String(command.op||"");
  if(op==="canvas.create"){await store.createProject();const created=useStore.getState().project;if(created&&command.name)await useStore.getState().renameProject(String(command.name),created.id);return{projectId:created?.id}}
  if(op==="canvas.open"){await store.openProject(String(command.projectId));return{projectId:String(command.projectId)}}
  if(op==="canvas.delete"){const projectId=String(command.projectId||store.project?.id||"");await store.deleteProject(projectId);return{deletedProjectId:projectId,currentProjectId:useStore.getState().project?.id}}
  if(op==="task.create"){const position=(command.position&&typeof command.position==="object"?command.position:{x:620,y:220}) as {x:number,y:number};await store.addTask(position,Array.isArray(command.sourceNodeIds)?command.sourceNodeIds.map(String):[]);const taskId=useStore.getState().selected[0];await useStore.getState().updateNode(taskId,{prompt:String(command.prompt||""),generationMode:command.generationMode==="browser"?"browser":"api",aspectRatio:String(command.aspectRatio||"auto")} as Partial<TaskNode>);return{taskId}}
  if(op==="task.run"){await store.runTask(String(command.taskId));const task=useStore.getState().project?.graph.nodes.find((node):node is TaskNode=>node.id===command.taskId&&node.kind==="task");return{taskId:String(command.taskId),status:task?.status}}
  if(op==="task.duplicate"){await store.duplicateTask(String(command.taskId));return{taskId:useStore.getState().selected[0]}}
  if(op==="task.delete"||op==="node.delete"){store.setSelected([String(command.taskId||command.nodeId)]);await useStore.getState().deleteSelected();return{deletedId:String(command.taskId||command.nodeId)}}
  if(op==="node.move"){await store.moveNode(String(command.nodeId),command.position as {x:number,y:number});return{nodeId:String(command.nodeId)}}
  if(op==="history.undo"){await store.restoreDeleted();return{undone:true}}
  if(op==="library.import")return importLibrary(command)
  if(op==="library.autoTagProducts"){const library=readLocalLibrary(),products=(library.media||[]).filter(item=>item.kind==="product"),preview=Boolean(command.preview),changes=[] as Array<Record<string,unknown>>;for(const item of products){const name=String(item.name||""),series=productSeriesTag(name),packaging=productPackageTag(name),before=normalizeTags(item.tags),managed=before.filter(tag=>!tag.endsWith("系列")&&tag!=="包装盒"&&tag!=="铝箔"),after=normalizeTags([...managed,...(series?[series]:[]),...(packaging?[packaging]:[])]);if(JSON.stringify(before)!==JSON.stringify(after))changes.push({id:item.id,name,before,after});if(!preview)item.tags=after}if(!preview)saveLocalLibrary(library);return{preview,total:products.length,changed:changes.length,unchanged:products.length-changes.length,unmatchedSeries:products.filter(item=>!productSeriesTag(String(item.name||""))).map(item=>({id:item.id,name:item.name})),unmatchedPackaging:products.filter(item=>!productPackageTag(String(item.name||""))).map(item=>({id:item.id,name:item.name})),changes}}
  throw new Error(`Unsupported Pixel Flow command: ${op}`);
}
async function handle(action:string,payload:Record<string,unknown>){if(action==="getState")return stateSnapshot();if(action==="getProducts")return{products:productSnapshot()};if(action==="getLibrary")return librarySnapshot(String(payload.scope||"all"));if(action==="getImage"){const project=useStore.getState().project,node=project?.graph.nodes.find(candidate=>candidate.id===payload.nodeId) as CanvasNode|undefined;if(!node||!(node.kind==="image"||node.kind==="result"))throw new Error("Image/result node was not found in the current canvas.");const asset=await db.assets.get(node.assetId);if(!asset)throw new Error("The image asset is missing.");return{nodeId:node.id,title:node.kind==="image"?node.title:(node.title||"生成结果"),dataUrl:await blobDataUrl(asset.blob)}}if(action==="execute"){const commands=Array.isArray(payload.commands)?payload.commands:[payload.commands];const results=[];for(const command of commands){if(!command||typeof command!=="object")throw new Error("Each command must be an object.");results.push(await executeOne(command as Record<string,unknown>))}return{results,state:stateSnapshot()}}throw new Error(`Unsupported bridge action: ${action}`)}

export function PixelFlowCodexBridge(){const socket=useRef<WebSocket|null>(null);useEffect(()=>{let stopped=false,timer=0;const sendStatus=()=>{const ws=socket.current,state=useStore.getState();if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"status",projectId:state.project?.id,revision:state.project?.updatedAt??0}))};const connect=()=>{if(stopped)return;const ws=new WebSocket(BRIDGE_URL);socket.current=ws;ws.onopen=()=>ws.send(JSON.stringify({type:"hello",clientId:clientId(),projectId:useStore.getState().project?.id,title:document.title,revision:revision()}));ws.onmessage=async event=>{let message;try{message=JSON.parse(String(event.data))}catch{return}if(message.type!=="task")return;try{const result=await handle(String(message.action),message.payload||{});ws.send(JSON.stringify({type:"result",requestId:message.requestId,result,revision:revision()}))}catch(error){ws.send(JSON.stringify({type:"result",requestId:message.requestId,error:error instanceof Error?error.message:String(error),revision:revision()}))}};ws.onclose=()=>{if(!stopped)timer=window.setTimeout(connect,1500)}};connect();const heartbeat=window.setInterval(sendStatus,10_000);const unsubscribe=useStore.subscribe(sendStatus);return()=>{stopped=true;window.clearTimeout(timer);window.clearInterval(heartbeat);unsubscribe();socket.current?.close()}},[]);return null}
