import { create } from "zustand";
import { db, id } from "./db";
import type { CanvasEdge, CanvasNode, ImageContainerNode, Point, Project, TaskNode } from "./types";

type Store = {
  projects: Project[]; project?: Project; assets: Record<string, string>; selected: string[]; ready: boolean; error?: string; undoDelete?: DeletedSnapshot;
  initialize(): Promise<void>; refresh(projectId?: string): Promise<void>; createProject(): Promise<void>; openProject(id: string): Promise<void>; renameProject(name: string, projectId?: string): Promise<void>; deleteProject(projectId?: string): Promise<void>;
  addTask(position: Point, sourceNodeIds?: string[]): Promise<void>; addImageContainer(position: Point, sourceNodeIds?: string[]): Promise<void>; addText(position: Point): Promise<void>; addTextContent(text: string, position: Point): Promise<void>; addImage(file: File, position: Point, targetTaskId?: string): Promise<void>; addImages(files: File[], position: Point, targetTaskId?: string): Promise<void>; addExistingAsset(assetId: string, title: string, position: Point, targetTaskId?: string): Promise<void>; addExistingAssetToContainer(assetId: string, title: string, containerId: string): Promise<void>;
  updateNode(nodeId: string, patch: Partial<CanvasNode>): Promise<void>; moveNode(nodeId: string, position: Point): Promise<void>; moveImageToContainer(imageId: string, containerId: string): Promise<void>; removeImageFromContainer(containerId: string, itemId: string, position: Point): Promise<void>; connect(source: string, target: string): Promise<void>; disconnectEdge(edgeId: string): Promise<void>;
  applyPromptToTask(taskId: string, content: string, mode: "replace" | "append"): Promise<boolean>; setSelected(ids: string[]): void; copySelected(): number; hasCopied(): boolean; prefersCopied(): boolean; preferExternalPaste(): void; copySelectedImageToSystemClipboard(): Promise<boolean>; pasteCopied(): Promise<void>; deleteSelected(): Promise<void>; restoreDeleted(): Promise<void>; duplicateTask(taskId: string): Promise<void>; runTask(taskId: string): Promise<void>; openTask(taskId: string): Promise<void>; hibernate(): Promise<number>; backup(): Promise<void>;
};

type DeletedSnapshot = { projectId: string; nodes: CanvasNode[]; edges: CanvasEdge[]; inputOrders: Record<string,string[]> };
type CopyableNode = Extract<CanvasNode,{kind:"image"|"result"|"image_container"}>;

let canvasClipboard: { nodes: CopyableNode[]; pasteCount: number; preferInternal: boolean } = { nodes: [], pasteCount: 0, preferInternal: false };

const clipboardPng = async (blob: Blob) => {
  if (blob.type === "image/png") return blob;
  const bitmap = await createImageBitmap(blob);
  const canvas = new OffscreenCanvas(bitmap.width,bitmap.height);
  canvas.getContext("2d")?.drawImage(bitmap,0,0);
  bitmap.close();
  return canvas.convertToBlob({type:"image/png"});
};

const clipboardComposite = async (blobs: Blob[]) => {
  const bitmaps=await Promise.all(blobs.map(blob=>createImageBitmap(blob)));
  const columns=Math.min(3,bitmaps.length),rows=Math.ceil(bitmaps.length/columns),cell=512,gap=16;
  const canvas=new OffscreenCanvas(columns*cell+(columns-1)*gap,rows*cell+(rows-1)*gap),context=canvas.getContext("2d")!;
  context.fillStyle="#ffffff";context.fillRect(0,0,canvas.width,canvas.height);
  bitmaps.forEach((bitmap,index)=>{const scale=Math.min(cell/bitmap.width,cell/bitmap.height),width=bitmap.width*scale,height=bitmap.height*scale,column=index%columns,row=Math.floor(index/columns);context.drawImage(bitmap,column*(cell+gap)+(cell-width)/2,row*(cell+gap)+(cell-height)/2,width,height);bitmap.close()});
  return canvas.convertToBlob({type:"image/png"});
};

const assetUrls = new Map<string,string>();
const urlsFor = async (project: Project) => {
  const wanted = new Set(project.graph.nodes.flatMap(node => node.kind === "image" || node.kind === "result" ? [node.assetId] : node.kind === "image_container" ? node.items.map(item=>item.assetId) : []));
  for (const [assetId,url] of assetUrls) if (!wanted.has(assetId)) { URL.revokeObjectURL(url); assetUrls.delete(assetId); }
  const entries = await Promise.all([...wanted].map(async assetId => {
    let url = assetUrls.get(assetId);
    if (!url) { const asset = await db.assets.get(assetId); if (!asset) return; url = URL.createObjectURL(asset.blob); assetUrls.set(assetId,url); }
    return [assetId,url] as const;
  }));
  return Object.fromEntries(entries.filter(Boolean) as Array<readonly [string,string]>);
};
let initialization: Promise<void> | undefined;
const mutate = async (projectId: string, fn: (project: Project) => Project) => db.transaction("rw", db.projects, async () => {
  const current = await db.projects.get(projectId); if (!current) throw new Error("找不到画布项目");
  const next = { ...fn(structuredClone(current)), updatedAt: Date.now() }; await db.projects.put(next); return next;
});

const normalizeBatchProject = (project: Project): Project => {
  const children = new Map(project.graph.nodes.filter((node): node is TaskNode => node.kind === "task" && Boolean(node.batchParentTaskId)).map(node => [node.id, node]));
  if (!children.size) return project;
  let changed = false;
  const nodes = project.graph.nodes.map(node => {
    if (node.kind === "result") {
      const child = children.get(node.taskId);
      if (child?.batchParentTaskId) { changed = true; return { ...node, taskId: child.batchParentTaskId }; }
    }
    if (node.kind === "task" && node.batchItems?.length) {
      const items = node.batchItems.map(item => {
        const child = item.taskId ? children.get(item.taskId) : undefined;
        return child && child.status !== item.status ? { ...item, status: child.status as TaskNode["status"] & typeof item.status, detail: child.statusDetail } : item;
      });
      const completed = items.filter(item => item.status === "completed").length;
      const failed = items.filter(item => item.status === "failed" || item.status === "manual_action").length;
      const active = items.some(item => ["queued", "waiting_page", "uploading", "sending", "generating"].includes(item.status));
      const status = completed === items.length ? "completed" : active ? "generating" : failed ? "failed" : node.status;
      if (items.some((item,index) => item !== node.batchItems![index]) || status !== node.status) { changed = true; return { ...node, batchItems: items, status, statusDetail: failed && !active ? `${completed}/${items.length} 完成，${failed} 项失败` : undefined }; }
    }
    return node;
  });
  const edges = project.graph.edges.map(edge => {
    if (edge.kind === "output") {
      const child = children.get(edge.source);
      if (child?.batchParentTaskId) { changed = true; return { ...edge, source: child.batchParentTaskId }; }
    }
    return edge;
  });
  return changed ? { ...project, graph: { nodes, edges }, updatedAt: Date.now() } : project;
};

export const useStore = create<Store>((set,get) => ({
  projects: [], assets: {}, selected: [], ready: false,
  hasCopied(){return Boolean(canvasClipboard.nodes.length)},
  prefersCopied(){return Boolean(canvasClipboard.nodes.length&&canvasClipboard.preferInternal)},
  preferExternalPaste(){canvasClipboard.preferInternal=false},
  async initialize() {
    if (!initialization) initialization = (async () => {
      let projects = await db.projects.orderBy("updatedAt").reverse().toArray();
      if (!projects.length) { const now=Date.now(); await db.projects.add({id:id("project"),name:"我的第一个画布",graph:{nodes:[],edges:[]},createdAt:now,updatedAt:now}); projects=await db.projects.orderBy("updatedAt").reverse().toArray(); }
      const project=normalizeBatchProject(projects[0]); if(project!==projects[0])await db.projects.put(project); set({projects,project,assets:await urlsFor(project),ready:true});
      if (globalThis.chrome?.runtime?.id) chrome.runtime.onMessage.addListener((message) => { if (message?.persisted && message.projectId===get().project?.id) void get().refresh(message.projectId); });
    })();
    return initialization;
  },
  async refresh(projectId) { const loaded=await db.projects.get(projectId??get().project?.id??""); if(!loaded)return;const project=normalizeBatchProject(loaded);if(project!==loaded)await db.projects.put(project); set({project,projects:await db.projects.orderBy("updatedAt").reverse().toArray(),assets:await urlsFor(project)}); },
  async createProject(){const now=Date.now(),project={id:id("project"),name:`新画布 ${get().projects.length+1}`,graph:{nodes:[],edges:[]},createdAt:now,updatedAt:now};await db.projects.add(project);set({project,projects:await db.projects.orderBy("updatedAt").reverse().toArray(),assets:{},selected:[]});},
  async openProject(projectId){const loaded=await db.projects.get(projectId);if(loaded){const project=normalizeBatchProject(loaded);if(project!==loaded)await db.projects.put(project);set({project,assets:await urlsFor(project),selected:[]})}},
  async renameProject(name,projectId){const targetId=projectId??get().project?.id;const nextName=name.trim();if(!targetId||!nextName)return;const renamed=await mutate(targetId,x=>({...x,name:nextName}));const projects=await db.projects.orderBy("updatedAt").reverse().toArray();set(s=>({projects,project:s.project?.id===renamed.id?renamed:s.project}));},
  async deleteProject(projectId){const targetId=projectId??get().project?.id;if(!targetId)return;const target=await db.projects.get(targetId);if(!target)return;for(const task of target.graph.nodes.filter((node):node is TaskNode=>node.kind==="task")){if(globalThis.chrome?.runtime?.id)await chrome.runtime.sendMessage({type:"CANCEL_TASK",projectId:targetId,taskId:task.id}).catch(()=>{})}await db.transaction("rw",db.projects,db.runs,async()=>{await db.projects.delete(targetId);const runs=(await db.runs.toArray()).filter(run=>run.projectId===targetId);await db.runs.bulkDelete(runs.map(run=>run.id))});let projects=await db.projects.orderBy("updatedAt").reverse().toArray();if(!projects.length){const now=Date.now(),fallback:Project={id:id("project"),name:"我的第一个画布",graph:{nodes:[],edges:[]},createdAt:now,updatedAt:now};await db.projects.add(fallback);projects=[fallback]}const project=get().project?.id===targetId?projects[0]:get().project??projects[0];set({projects,project,assets:await urlsFor(project),selected:[]});},
  async addTask(position,sourceNodeIds=[]){const p=get().project;if(!p)return;const count=p.graph.nodes.filter(n=>n.kind==="task").length+1;const sources=p.graph.nodes.filter((node):node is Extract<CanvasNode,{kind:"image"|"result"|"image_container"}>=>(sourceNodeIds.includes(node.id)&&(node.kind==="image"||node.kind==="result"||node.kind==="image_container")));const placed=sources.length?{x:Math.max(...sources.map(source=>source.position.x+(source.width??320)))+80,y:Math.min(...sources.map(source=>source.position.y))}:{...position};if(!sources.length){const occupied=p.graph.nodes.filter((node):node is TaskNode=>node.kind==="task");let offset=0;while(occupied.some(node=>Math.abs(node.position.x-(placed.x+offset))<280&&Math.abs(node.position.y-(placed.y+offset))<180))offset+=48;placed.x+=offset;placed.y+=offset}const task:TaskNode={id:id("task"),kind:"task",name:`生图任务 ${String(count).padStart(2,"0")}`,prompt:"",position:placed,inputEdgeOrder:[],runCount:0,status:"idle",aspectRatio:"auto",generationMode:"api"};const project=await mutate(p.id,x=>{const currentSources=x.graph.nodes.filter(node=>sourceNodeIds.includes(node.id)&&(node.kind==="image"||node.kind==="result"||node.kind==="image_container"));const edges=currentSources.map(source=>({id:id("edge"),source:source.id,target:task.id,kind:"input" as const}));return{...x,graph:{nodes:[...x.graph.nodes,task].map(node=>node.id===task.id?{...node,inputEdgeOrder:edges.map(edge=>edge.id)}:node),edges:[...x.graph.edges,...edges]}}});set({project,selected:[task.id]});},
  async addImageContainer(position,sourceNodeIds=[]){const p=get().project;if(!p)return;const members=p.graph.nodes.filter((node):node is Extract<CanvasNode,{kind:"image"|"result"}>=>(sourceNodeIds.includes(node.id)&&(node.kind==="image"||node.kind==="result")));const container:ImageContainerNode={id:id("image-container"),kind:"image_container",name:`图片容器 ${p.graph.nodes.filter(node=>node.kind==="image_container").length+1}`,items:members.map(node=>({id:id("container-item"),assetId:node.assetId,title:node.kind==="result"?(node.title||"生成结果"):node.title})),position,width:360,height:members.length?210:150};const project=await mutate(p.id,x=>{const selected=new Set(members.map(node=>node.id));return{...x,graph:{nodes:[...x.graph.nodes.filter(node=>!selected.has(node.id)),container],edges:x.graph.edges.filter(edge=>!selected.has(edge.source)&&!selected.has(edge.target)).map(edge=>edge)}}});set({project,selected:[container.id],assets:await urlsFor(project)});},
  async addText(position){const p=get().project;if(!p)return;const node:CanvasNode={id:id("text"),kind:"text",text:"",position};const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:[...x.graph.nodes,node]}}));set({project});},
  async addTextContent(text,position){const p=get().project,content=text.trim();if(!p||!content)return;const node:CanvasNode={id:id("text"),kind:"text",text:content,position};const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:[...x.graph.nodes,node]}}));set({project,selected:[node.id]});},
  async addImage(file,position,targetTaskId){await get().addImages([file],position,targetTaskId)},
  async addImages(files,position,targetTaskId){const p=get().project;const images=files.filter(file=>file.type.startsWith("image/"));if(!p||!images.length)return;const records=images.map((file,index)=>({file,assetId:id("asset"),nodeId:id("image"),position:{x:position.x+(index%3)*240,y:position.y+Math.floor(index/3)*180}}));await db.transaction("rw",db.assets,async()=>{for(const record of records)await db.assets.add({id:record.assetId,blob:record.file,createdAt:Date.now()})});const nodes:CanvasNode[]=records.map(record=>({id:record.nodeId,kind:"image",assetId:record.assetId,title:record.file.name,position:record.position}));const project=await mutate(p.id,x=>{const target=targetTaskId?x.graph.nodes.find(item=>item.id===targetTaskId&&item.kind==="task") as TaskNode|undefined:undefined;if(!target)return{...x,graph:{...x.graph,nodes:[...x.graph.nodes,...nodes]}};const edges=nodes.map(node=>({id:id("edge"),source:node.id,target:target.id,kind:"input" as const}));return{...x,graph:{nodes:[...x.graph.nodes,...nodes].map(item=>item.id===target.id&&item.kind==="task"?{...item,inputEdgeOrder:[...item.inputEdgeOrder,...edges.map(edge=>edge.id)]}:item),edges:[...x.graph.edges,...edges]}}});const urls=Object.fromEntries(records.map(record=>{const url=URL.createObjectURL(record.file);assetUrls.set(record.assetId,url);return[record.assetId,url]}));set(s=>({project,assets:{...s.assets,...urls},selected:targetTaskId?[targetTaskId]:nodes.map(node=>node.id)}));},
  async addExistingAsset(assetId,title,position,targetTaskId){const p=get().project;if(!p||!await db.assets.get(assetId))return;const node:CanvasNode={id:id("image"),kind:"image",assetId,title,position};const project=await mutate(p.id,x=>{const target=targetTaskId?x.graph.nodes.find(item=>item.id===targetTaskId&&item.kind==="task") as TaskNode|undefined:undefined;if(!target)return{...x,graph:{...x.graph,nodes:[...x.graph.nodes,node]}};const edge:CanvasEdge={id:id("edge"),source:node.id,target:target.id,kind:"input"};return{...x,graph:{nodes:[...x.graph.nodes,node].map(item=>item.id===target.id&&item.kind==="task"?{...item,inputEdgeOrder:[...item.inputEdgeOrder,edge.id]}:item),edges:[...x.graph.edges,edge]}}});set({project,assets:await urlsFor(project),selected:[node.id]});},
  async addExistingAssetToContainer(assetId,title,containerId){const p=get().project;if(!p||!await db.assets.get(assetId)||!p.graph.nodes.some(node=>node.id===containerId&&node.kind==="image_container"))return;const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:x.graph.nodes.map(node=>node.id===containerId&&node.kind==="image_container"?{...node,items:[...node.items,{id:id("container-item"),assetId,title}]}:node)}}));set({project,assets:await urlsFor(project),selected:[containerId]});},
  async applyPromptToTask(taskId,content,mode){const p=get().project,prompt=content.trim();if(!p||!prompt)return false;const task=p.graph.nodes.find(node=>node.id===taskId&&node.kind==="task") as TaskNode|undefined;if(!task)return false;const next=mode==="append"&&task.prompt.trim()?`${task.prompt.trim()}\n\n${prompt}`:prompt;const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:x.graph.nodes.map(node=>node.id===taskId&&node.kind==="task"?{...node,prompt:next}:node)}}));set({project});return true;},
  async updateNode(nodeId,patch){const p=get().project;if(!p)return;const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:x.graph.nodes.map(n=>n.id===nodeId?{...n,...patch} as CanvasNode:n)}}));set({project});},
  async moveNode(nodeId,position){const p=get().project;const moving=p?.graph.nodes.find(node=>node.id===nodeId);const container=p?.graph.nodes.find((node):node is ImageContainerNode=>node.kind==="image_container"&&node.id!==nodeId&&(moving?.kind==="image"||moving?.kind==="result")&&position.x<(node.position.x+(node.width??360))&&position.x+(moving.width??320)>node.position.x&&position.y<(node.position.y+(node.height??150))&&position.y+(moving.height??320)>node.position.y);if(moving&&(moving.kind==="image"||moving.kind==="result")&&container){await get().moveImageToContainer(nodeId,container.id);return}await get().updateNode(nodeId,{position} as Partial<CanvasNode>);},
  async moveImageToContainer(imageId,containerId){const p=get().project;if(!p)return;const image=p.graph.nodes.find((node):node is Extract<CanvasNode,{kind:"image"|"result"}>=>node.id===imageId&&(node.kind==="image"||node.kind==="result"));const container=p.graph.nodes.find(node=>node.id===containerId&&node.kind==="image_container") as ImageContainerNode|undefined;if(!image||!container)return;const project=await mutate(p.id,x=>({...x,graph:{nodes:x.graph.nodes.filter(node=>node.id!==imageId).map(node=>node.id===containerId&&node.kind==="image_container"?{...node,items:[...node.items,{id:id("container-item"),assetId:image.assetId,title:image.kind==="result"?(image.title||"生成结果"):image.title}]}:node),edges:x.graph.edges.filter(edge=>edge.source!==imageId&&edge.target!==imageId)}}));set({project,selected:[containerId],assets:await urlsFor(project)});},
  async removeImageFromContainer(containerId,itemId,position){const p=get().project;if(!p)return;const container=p.graph.nodes.find(node=>node.id===containerId&&node.kind==="image_container") as ImageContainerNode|undefined;const item=container?.items.find(candidate=>candidate.id===itemId);if(!container||!item)return;const node:CanvasNode={id:id("image"),kind:"image",assetId:item.assetId,title:item.title,position};const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:x.graph.nodes.map(candidate=>candidate.id===containerId&&candidate.kind==="image_container"?{...candidate,items:candidate.items.filter(entry=>entry.id!==itemId)}:candidate).concat(node)}}));set({project,selected:[node.id],assets:await urlsFor(project)});},
  async connect(source,target){const p=get().project;if(!p||source===target)return;const edge:CanvasEdge={id:id("edge"),source,target,kind:"input"};const project=await mutate(p.id,x=>({...x,graph:{...x.graph,edges:[...x.graph.edges,edge],nodes:x.graph.nodes.map(n=>n.id===target&&n.kind==="task"?{...n,inputEdgeOrder:[...n.inputEdgeOrder,edge.id]}:n)}}));set({project});},
  async disconnectEdge(edgeId){const p=get().project;if(!p)return;const edge=p.graph.edges.find(item=>item.id===edgeId);if(!edge||edge.kind==="output")return;const project=await mutate(p.id,x=>({...x,graph:{edges:x.graph.edges.filter(item=>item.id!==edgeId),nodes:x.graph.nodes.map(node=>node.kind==="task"?{...node,inputEdgeOrder:node.inputEdgeOrder.filter(id=>id!==edgeId)}:node)}}));set({project});},
  setSelected(selected){set({selected});const p=get().project;if(!p)return;const task=p.graph.nodes.find(node=>selected.includes(node.id)&&node.kind==="task"&&!node.hidden) as TaskNode|undefined;const container=p.graph.nodes.find(node=>selected.includes(node.id)&&node.kind==="image_container") as ImageContainerNode|undefined;if(task&&container&&!p.graph.edges.some(edge=>edge.source===container.id&&edge.target===task.id))void get().connect(container.id,task.id);},
  copySelected(){const p=get().project;if(!p)return 0;const selected=new Set(get().selected);const nodes=p.graph.nodes.filter((node):node is CopyableNode=>selected.has(node.id)&&(node.kind==="image"||node.kind==="result"||node.kind==="image_container")).map(node=>structuredClone(node));canvasClipboard={nodes,pasteCount:0,preferInternal:Boolean(nodes.length)};return nodes.length;},
  async copySelectedImageToSystemClipboard(){const p=get().project,selected=get().selected;if(!p||selected.length!==1||!navigator.clipboard?.write||typeof ClipboardItem==="undefined")return false;const node=p.graph.nodes.find((candidate):candidate is CopyableNode=>candidate.id===selected[0]&&(candidate.kind==="image"||candidate.kind==="result"||candidate.kind==="image_container"));if(!node)return false;const assetIds=node.kind==="image_container"?node.items.map(item=>item.assetId):[node.assetId];const assets=(await Promise.all(assetIds.map(assetId=>db.assets.get(assetId)))).filter(Boolean);if(!assets.length||assets.length!==assetIds.length)return false;try{const pngs=await Promise.all(assets.map(asset=>clipboardPng(asset!.blob)));try{await navigator.clipboard.write(pngs.map(png=>new ClipboardItem({"image/png":png})));return true}catch{const composite=await clipboardComposite(pngs);await navigator.clipboard.write([new ClipboardItem({"image/png":composite})]);return true}}catch{return false}},
  async pasteCopied(){const p=get().project;if(!p||!canvasClipboard.nodes.length)return;canvasClipboard.pasteCount+=1;const offset=36*canvasClipboard.pasteCount;const nodes:CanvasNode[]=canvasClipboard.nodes.map(node=>{const position={x:node.position.x+offset,y:node.position.y+offset};if(node.kind==="image_container")return{...structuredClone(node),id:id("image-container"),name:`${node.name} 副本`,items:node.items.map(item=>({...item,id:id("container-item")})),position};return{id:id("image"),kind:"image",assetId:node.assetId,title:node.kind==="result"?(node.title||"生成结果"):node.title,position,width:node.width,height:node.height}});const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:[...x.graph.nodes,...nodes]}}));set({project,selected:nodes.map(node=>node.id),assets:await urlsFor(project)});},
  async deleteSelected(){const p=get().project,ids=new Set(get().selected);if(!p||!ids.size)return;for(const n of p.graph.nodes)if(ids.has(n.id)&&n.kind==="task"&&globalThis.chrome?.runtime?.id)await chrome.runtime.sendMessage({type:"CANCEL_TASK",projectId:p.id,taskId:n.id}).catch(()=>{});const removedEdges=p.graph.edges.filter(edge=>ids.has(edge.source)||ids.has(edge.target));const removedEdgeIds=new Set(removedEdges.map(edge=>edge.id));const snapshot:DeletedSnapshot={projectId:p.id,nodes:p.graph.nodes.filter(node=>ids.has(node.id)).map(node=>structuredClone(node)),edges:removedEdges.map(edge=>structuredClone(edge)),inputOrders:Object.fromEntries(p.graph.nodes.filter((node):node is TaskNode=>node.kind==="task"&&node.inputEdgeOrder.some(edgeId=>removedEdgeIds.has(edgeId))).map(node=>[node.id,[...node.inputEdgeOrder]]))};const project=await mutate(p.id,x=>({...x,graph:{nodes:x.graph.nodes.filter(n=>!ids.has(n.id)).map(node=>node.kind==="task"?{...node,inputEdgeOrder:node.inputEdgeOrder.filter(edgeId=>!removedEdgeIds.has(edgeId))}:node),edges:x.graph.edges.filter(e=>!ids.has(e.source)&&!ids.has(e.target))}}));set({project,selected:[],undoDelete:snapshot});},
  async restoreDeleted(){const snapshot=get().undoDelete,p=get().project;if(!snapshot||!p||snapshot.projectId!==p.id)return;const project=await mutate(p.id,x=>{const nodes=[...x.graph.nodes,...snapshot.nodes.filter(node=>!x.graph.nodes.some(current=>current.id===node.id))];const nodeIds=new Set(nodes.map(node=>node.id));const edges=[...x.graph.edges,...snapshot.edges.filter(edge=>nodeIds.has(edge.source)&&nodeIds.has(edge.target)&&!x.graph.edges.some(current=>current.id===edge.id))];const edgeIds=new Set(edges.map(edge=>edge.id));return{...x,graph:{edges,nodes:nodes.map(node=>node.kind==="task"&&snapshot.inputOrders[node.id]?{...node,inputEdgeOrder:snapshot.inputOrders[node.id].filter(edgeId=>edgeIds.has(edgeId))}:node)}}});set({project,selected:snapshot.nodes.map(node=>node.id),undoDelete:undefined,assets:await urlsFor(project)});},
  async duplicateTask(taskId){const p=get().project;if(!p)return;const source=p.graph.nodes.find(n=>n.id===taskId&&n.kind==="task") as TaskNode|undefined;if(!source)return;const copy={...source,id:id("task"),name:`${source.name} 副本`,position:{x:source.position.x+36,y:source.position.y+36},status:"idle" as const,runCount:0,conversationUrl:undefined,apiJobId:undefined,statusDetail:undefined,inputEdgeOrder:[]};const project=await mutate(p.id,x=>({...x,graph:{...x.graph,nodes:[...x.graph.nodes,copy]}}));set({project});},
  async runTask(taskId){const p=get().project;if(!p||!chrome.runtime?.id)return;const task=p.graph.nodes.find(node=>node.id===taskId&&node.kind==="task") as TaskNode|undefined;if(!task)return;const containerEdges=p.graph.edges.filter(edge=>edge.target===taskId&&p.graph.nodes.some(node=>node.id===edge.source&&node.kind==="image_container"));const container=containerEdges.length?p.graph.nodes.find(node=>node.id===containerEdges[0].source&&node.kind==="image_container") as ImageContainerNode|undefined:undefined;if(!container?.items.length){await get().updateNode(taskId,{status:"queued",statusDetail:undefined} as Partial<TaskNode>);await chrome.runtime.sendMessage({type:"RUN_TASK",projectId:p.id,taskId});return}const sharedEdges=task.inputEdgeOrder.filter(edgeId=>!containerEdges.some(edge=>edge.id===edgeId)).map(edgeId=>p.graph.edges.find(edge=>edge.id===edgeId)).filter(Boolean) as CanvasEdge[];const children=container.items.map((item,index)=>{const imageId=id("batch-image"),childId=id("batch-task"),edge={id:id("edge"),source:imageId,target:childId,kind:"input" as const},sharedChildEdges=sharedEdges.map(sharedEdge=>({...sharedEdge,id:id("edge"),target:childId}));return{item,image:{id:imageId,kind:"image" as const,assetId:item.assetId,title:item.title,hidden:true,position:{x:task.position.x-1000,y:task.position.y+index*12}},task:{...task,id:childId,name:`${task.name} · ${index+1}/${container.items.length}`,position:{x:task.position.x,y:task.position.y},inputEdgeOrder:[...sharedChildEdges.map(sharedEdge=>sharedEdge.id),edge.id],runCount:0,status:"idle" as const,conversationUrl:undefined,apiJobId:undefined,statusDetail:undefined,batchItems:undefined,batchParentTaskId:task.id,batchItemId:item.id,hidden:true},edge,sharedChildEdges}});const project=await mutate(p.id,x=>({...x,graph:{nodes:x.graph.nodes.map(node=>node.id===task.id&&node.kind==="task"?{...node,status:"queued",statusDetail:undefined,batchItems:children.map(child=>({id:child.item.id,title:child.item.title,status:"queued" as const,taskId:child.task.id}))}:node).concat(children.flatMap(child=>[child.image,child.task])),edges:[...x.graph.edges,...children.flatMap(child=>[...child.sharedChildEdges,child.edge])]}}));set({project});await Promise.all(children.map(child=>chrome.runtime.sendMessage({type:"RUN_TASK",projectId:p.id,taskId:child.task.id})));},
  async openTask(taskId){const p=get().project;if(p&&chrome.runtime?.id)await chrome.runtime.sendMessage({type:"OPEN_TASK_TAB",projectId:p.id,taskId});},
  async hibernate(){const p=get().project;if(!p||!chrome.runtime?.id)return 0;const taskIds=p.graph.nodes.filter(n=>n.kind==="task"&&!(["queued","waiting_page","uploading","sending","generating"] as string[]).includes(n.status)).map(n=>n.id);const r=await chrome.runtime.sendMessage({type:"HIBERNATE_TASK_TABS",projectId:p.id,taskIds});return r?.released??0;},
  async backup(){const p=get().project;if(!p)return;const payload={version:1,project:p,assets:await Promise.all(p.graph.nodes.flatMap(n=>n.kind==="image"||n.kind==="result"?[db.assets.get(n.assetId).then(async a=>a?{id:a.id,type:a.blob.type,data:Array.from(new Uint8Array(await a.blob.arrayBuffer()))}:null)]:[]))};const blob=new Blob([JSON.stringify(payload)],{type:"application/json"});const url=URL.createObjectURL(blob);await chrome.downloads?.download({url,filename:`${p.name}.gptcanvas.json`,saveAs:true});setTimeout(()=>URL.revokeObjectURL(url),30000);}
}));
